version: '2.1'

services:
  owncloud:
    environment:
      - OWNCLOUD_APPS_INSTALL=files_antivirus
    volumes:
      - ./configs/enable_files_antivirus_daemon.sh:/etc/pre_server.d/50-enable_files_antivirus_daemon.sh
